<?php
    // always order by groups first
    foreach($data->groups as $group):
        // at least one file in this group
        if(isset($data->files_in_this_group[$group['group_id']])):
?>
    <thead id="dlg_thead_gr<?php echo $group['group_id'] ?>">
        <tr>
            <th colspan="6" class="groupheader hide_on_mobile">
                <?php echo ( isset($data->gr2name[$group['group_id']]) ? $data->gr2name[$group['group_id']] : $TEXT['NONE'] ) ?>
            </th>
        </tr>
        <tr>
            <th class="hide_on_mobile"></th>
            <th class="th_name"><?php echo $DGTEXT['THTITLE'] ?></th>
            <th class="th_modified hide_on_mobile"><?php echo $DGTEXT['THCHANGED'] ?></th>
            <th class="th_released hide_on_mobile"><?php echo $DGTEXT['THRELEASED'] ?></th>
            <th class="th_size"><?php echo $DGTEXT['THSIZE'] ?></th>
            <th class="th_dlcount hide_on_mobile"><?php echo $DGTEXT['THCOUNT'] ?></th>
        </tr>
    </thead>
    <tbody id="dlg_tbody_gr<?php echo $group['group_id'] ?>">
<?php
    // inside group, show files by configured order
                foreach($data->files as $i => $file):
                    // not this group
                    if($file['group_id']!=$group['group_id']):
                        continue;
                    endif;
                    // set the icon for the current file type
                    $image = ( isset($data->ext2img[$file['extension']]) ? $data->ext2img[$file['extension']] : 'unknown.gif' );
?>
        <tr class="dlg3item<?php if($i % 2): echo ' row_a'; endif; ?>" id="td_<?php echo $file['file_id'] ?>">
            <td rowspan="2" style="vertical-align:top" class="hide_on_mobile">
                <img src="<?php echo WB_URL ?>/modules/<?php echo $dlgmodname; ?>/images/<?php echo $image ?>" alt="" />
            </td>
            <td class="item_name" data-th="<?php echo $DGTEXT['THTITLE'] ?>">
                <a href="<?php echo $data->self_link ?>?dl=<?php echo $file['file_id'] ?>"><?php echo $file['title'] ?></a>
            </td>
            <td class="hide_on_mobile item_modified" data-th="<?php echo $DGTEXT['THCHANGED'] ?>"><?php echo date(DATE_FORMAT, $file['modified_when']) ?></td>
            <td class="hide_on_mobile item_released" data-th="<?php echo $DGTEXT['THRELEASED'] ?>"><?php echo ( $file['released'] != 0 ? date(DATE_FORMAT, $file['released']) : '' ) ?></td>
            <td class="item_size" data-th="<?php echo $DGTEXT['THSIZE'] ?>"><?php echo ( ( $file['size'] > 0 ) ? hfs($file['size'],$data->settings['file_size_roundup'],$data->settings['file_size_decimals']) : 0 )?></td>
            <td class="hide_on_mobile item_dlcount" data-th="<?php echo $DGTEXT['THCOUNT'] ?>"><?php echo $file['dlcount'] ?></td>
        </tr>
        <tr<?php if($i % 2): echo ' class="row_a"'; endif; ?> id="td2_<?php echo $file['file_id'] ?>">
            <td class="item_description" colspan="5" data-th="<?php echo $TEXT['DESCRIPTION'] ?>"><?php echo $file['description'] ?></td>
        </tr>
<?php
            endforeach;  // files
?>
    </tbody>
<?php
        endif;
    endforeach;      // groups
?>
