<div class="mod_downloadgallery" id="dlg<?=  $section_id ?>">
<?php if($data->settings['tplcss'] == 'Y'): /* add optional CSS to the header */ ?>
    <script type="text/javascript">
    //<![CDATA[
        var fileref=document.createElement("link");
        fileref.setAttribute("rel", "stylesheet");
        fileref.setAttribute("type", "text/css");
        fileref.setAttribute("href", "<?=  WB_URL ?>/modules/<?=  $dlgmodname; ?>/templates/default/frontend/<?=  $data->settings['tpldir'] ?>/style.css");
        document.getElementsByTagName("head")[0].appendChild(fileref);
    //]]>
    </script>
<?php endif; ?>

<?php
    if($data->filecount != 0):
        if($data->settings['search_filter'] == 'Y'): /* add optional search box */
?>
    <div>
        <div style="float:left">
            <label for="dlg_filter_<?=  $section_id ?>" title="<?=  $DGTEXT['FILTER_INLINE_NOTE'] ?>"><span class="dlg-filter"><?= $DGTEXT['FILTER'] ?></span></label>
            <input class="filter" id="dlg_filter_<?=  $section_id ?>" placeholder="<?=  $DGTEXT['FILTER'] ?>" />
        </div>
<?php if($data->filecount != $data->num_files): ?>
        <div style="float:right;">
            <form method="post" action="<?=  $data->self_link ?>">
                <input type="hidden" name="page" id="page" value="<?=  $current_page?>" />
                <label for="dlg_search_<?=  $section_id ?>" title="<?=  $DGTEXT['SEARCH_NOTE'] ?>"><span class="dlg-search"></span></label>
                <input class="search" id="dlg_search_<?=  $section_id ?>" name="dlg_search_<?=  $section_id ?>" placeholder="<?=  $DGTEXT['SEARCH'] ?>" />
                <input type="submit" value="Suchen" />
            </form>
        </div>
<?php endif; /* $data->filecount != $data->num_files */ ?>
    </div><br style="clear:both" />
<?php if($data->searchfor): ?>
    <div class="dlg_search_result">
        <?=  $DGTEXT['SEARCHMATCH'], ' ', $data->num_files, ' ', $DGTEXT['OUT_OF1'], ' "', $data->searchfor, '" ', $DGTEXT['OUT_OF2'], ' ', $DGTEXT['ITEMS']; ?>
        <a class="dlg_button" href="<?=  $data->self_link ?>">Suche zurücksetzen</a>
    </div>
<?php endif; ?>
<?php endif; /* $data->settings['search_filter'] */ ?>

    <table class="rwd-table">
        <?php $lastgroup = -1; ?>
        <?php include 'files_loop.phtml' ?>
        <tfoot>
            <tr>
                <td colspan="6" class="hide_on_mobile"></td>
            </tr>
        </tfoot>
    </table><br />

<?php if($data->num_files != $data->filecount): /* show paging only if there are more files */ ?>
    <div class="center"><?=  $DGTEXT['SHOWING'] ?></div><br />
    <nav role="navigation">
	<ul class="bullets">
            <li class="prev">
                <?php if($data->prev): ?>
                <a href="<?=  $data->self_link ?>?page=<?=  $data->prev?>">&laquo; <?=  $DGTEXT['PREVIOUS'] ?></a>
                <?php else: echo '&nbsp;'; endif; ?>
            </li>
<?php foreach($data->nav_pages as $number): ?>
            <li<?php if($number == $data->page): ?> class="current"<?php endif; ?>>
                <a href="<?=  $data->self_link ?>?page=<?=  $number?>"><?=  $number?></a>
            </li>
<?php endforeach; ?>
            <li class="next">
                <?php if($data->next): ?>
                <a href="<?=  $data->self_link ?>?page=<?=  $data->next?>"><?=  $DGTEXT['NEXT'] ?> &raquo;</a>
                <?php else: echo '&nbsp;'; endif; ?>
            </li>
        </ul>
	</nav>
<?php endif; /* $data->num_files != $data->filecount */ else: ?>
    <div class="info"><?=  $DGTEXT['FILE_NO_FILES'] ?></div>
<?php endif; ?>
</div>