<?php
    foreach($data->files as $i=>$file):
        $icon = $data->ext2img[$file['extension']];
        // if it's an image, show it
        if(in_array(strtolower($file['extension']),array('jpg','jpeg','gif','png'))):
            $link  = '<img src="'.$file['link'].'" alt="" />';
            $isimg = true;
        // otherwise, show file type
        else:
            $link  = '<div class="fi fi-'.$file['extension'].'"><div class="fi-content">'.$file['extension'].'</div></div>';
            $isimg = false;
        endif;
        
?>

<div class="dlg3item dlg3box">
    <div class="dlg3headimg">
        <?php echo $link ?>
    </div>
    <div class="dlg3title">
        <h3 style="font-size: 1.4em;"><a href="<?php echo $data->self_link ?>?dl=<?php echo $file['file_id'] ?>"><?php echo $file['title'] ?></a></h3>
    </div>
    <div class="dlg3subhead">
        
    </div>
    <div class="dlg3size">
        <div style="margin: 5px 0 5px 0; font-weight: bold;"><?php echo ( ( $file['size'] > 0 ) ? human_file_size($file['size']) : 0 )?></div>
    </div>
    <div class="dlg3body">
        <?php echo $file['description'] ?>
    </div>
    <div class="dlg3foot">
        <a href="<?php echo $data->self_link ?>?dl=<?php echo $file['file_id'] ?>" class="dlg3btn">DOWNLOAD</a>
    </div>
</div>

<?php endforeach; ?>