<div class="mod_downloadgallery" id="dlg<?php echo $section_id ?>">
<?php if($data->settings['tplcss'] == 'Y'): /* add optional CSS to the header */ ?>
    <script type="text/javascript">
    //<![CDATA[
        var fileref=document.createElement("link");
        fileref.setAttribute("rel", "stylesheet");
        fileref.setAttribute("type", "text/css");
        fileref.setAttribute("href", "<?php echo WB_URL ?>/modules/download_gallery/templates/frontend/<?php echo $data->settings['tpldir'] ?>/style.css");
        document.getElementsByTagName("head")[0].appendChild(fileref);
    //]]>
    </script>
<?php endif; ?>
<?php if($data->settings['search_filter']): /* add optional search box */ ?>
    <label for="dlg_search_<?php echo $section_id ?>" title="<?php echo $DGTEXT['FILTER_INLINE_NOTE'] ?>"><?php echo $DGTEXT['FILTER_INLINE'] ?></label>
    <input class="search" id="dlg_search_<?php echo $section_id ?>" placeholder="<?php echo $DGTEXT['FILTER'] ?>" />
<?php endif; ?>
    <table class="rwd-table">
        <?php $lastgroup = 0; ?>
        <?php include 'files_loop.phtml' ?>
    </table>

<?php if($data->currcount != $data->filecount): /* show paging only if there are more files */ ?>
    <nav role="navigation">
		<ul class="cd-pagination animated-buttons custom-icons">
			<li class="button"><a href="#0"><i>Prev</i></a></li>
            <li><?php echo $DGTEXT['SHOWING'] ?></li>
			<li class="button"><a href="#0"><i>Next</i></a></li>
		</ul>
	</nav>
<?php endif; ?>

    <script type="text/javascript">
    //<![CDATA[
        var lastlength = 0;
        document.getElementById('dlg_search_<?php echo $section_id ?>').addEventListener('keyup', function(e) {
            var target = e.target || e.srcElement;
            var search = target.value;
            var elems  = document.getElementById('dlg<?php echo $section_id ?>').getElementsByClassName('item_name');
            for(var i = 0; i < elems.length; i++)
            {
                var text = elems[i].textContent.toLowerCase();
                // elems[i].parentNode is the <tr>
                var next_node_id = elems[i].parentNode.id.replace('td_','td2_');
                if(text.indexOf(search) == -1) {
                    elems[i].parentElement.style.display='none';
                    document.getElementById(next_node_id).style.display='none';
                } else {
                    elems[i].parentElement.style.display='table-row';
                    document.getElementById(next_node_id).style.display='table-row';
                }
            }
            // hide empty groups
            var groupheaders = document.getElementsByClassName('groupheader');
            for(var l=0;l<groupheaders.length;l++)
            {
                // find next tbody
                var tbody = document.getElementById( groupheaders[l].parentNode.parentNode.id.replace('thead','tbody') );
                // count tr's
                var trcount = tbody.getElementsByTagName('tr').length;
                var hidden  = 0;
                for(n=0;n<tbody.getElementsByTagName('tr').length;n++)
                {
                    if(tbody.getElementsByTagName('tr')[n].style.display == 'none')
                    {
                        hidden++;
                    }
                }
                if(trcount==hidden)
                {
                    groupheaders[l].parentNode.parentNode.style.display='none';
                }
                else
                {
                    groupheaders[l].parentNode.parentNode.style.display='table-header-group';
                }
            }
            lastlength = search.length;
        });
    //]]>
    </script>
</div>