<div class="mod_download_gallery">
	<h1><?php echo $DGTEXT['MOD_FILE_EXT']; ?></h1>
	<p><?php echo $DGTEXT['MOD_TXT']; ?></p>

<?php if($data->infotext): ?>
    <div class="info"><?php echo $data->infotext ?></div>
<?php endif; ?>

	<form name="modify_file_ext" method="post" action="<?php echo WB_URL; ?>/modules/download_gallery/modify_extensions.php">
		<input type="hidden" name="section_id" value="<?php echo $section_id; ?>" />
		<input type="hidden" name="page_id" value="<?php echo $page_id; ?>" />
		<input type="hidden" name="fileext_id" value="<?php echo $data->extdetails['fileext_id']; ?>" />
		<table cellpadding="2" cellspacing="0" width="100%">
			<tr>
				<td width="150"><?php echo $DGTEXT['FILE_TYPE']; ?>:</td>
				<td><strong><?php echo $data->extdetails['file_type']; ?></strong></td>
			</tr>
			<tr>
				<td><?php echo $DGTEXT['FILE_TYPE_EXT']; ?>:</td>
			</tr>
			<tr>
				<td colspan="2">
					<textarea name="file_ext" style="width: 96%; height: 100px;"><?php echo str_replace(",",", ", $data->extdetails['extensions']); ?></textarea>
				</td>
			</tr>
		</table>
		<table cellpadding="0" cellspacing="0" border="0" width="100%">
			<tr>
				<td align="center">
					<input name="save" type="submit" value="<?php echo $TEXT['SAVE']; ?>" style="width: 120px; margin-top: 5px;" /> &nbsp;
					<input type="button" value="<?php echo $TEXT['CANCEL']; ?>" onclick="javascript:window.location='<?php echo WB_URL; ?>/modules/download_gallery/modify_settings.php?page_id=<?php echo $page_id; ?>&section_id=<?php echo $section_id ?>';" style="width: 120px; margin-top: 5px;" />
				</td>
			</tr>
		</table>
	</form>
</div>
