<div class="mod_download_gallery">
    <script type="text/javascript">
    //<![CDATA[
    function process(element){
    	switch(element.value){
    		case "0":
    			document.getElementById('extorder').style.display = "none";
    			break;
    		case "1":
    			document.getElementById('extorder').style.display = "";
    			break;
    	}
    }

    function process2(element){
    	switch(element.value){
    		case "0":
    			document.getElementById('tr_captcha').style.display = "none";
    			break;
    		case "1":
    		case "2":
    			document.getElementById('tr_captcha').style.display = "";
    			break;
    	}
    }
    //]]>
    </script>

    <form name="modify" action="<?php echo $data->self_link ?>/save_settings.php" method="post">
    	<input type="hidden" name="section_id" value="<?php echo $section_id; ?>" />
    	<input type="hidden" name="page_id" value="<?php echo $page_id; ?>" />
        <?php if($data->FTAN): echo $data->FTAN; endif; ?>
    	<table class="settings">
            <thead>
        		<tr>
        			<th colspan="2"><?php echo $DGTEXT['GSETTINGS']; ?></th>
        		</tr>
            </thead>
            <tbody>
        		<tr>
        			<td width="25%"><label for="files_per_page"><?php echo $DGTEXT['FILES_PER_PAGE']; ?>:</label></td>
        			<td><input type="text" id="files_per_page" name="files_per_page" value="<?php echo $data->settings['files_per_page']; ?>" style="width: 30px" /> 0 = <?php echo $TEXT['UNLIMITED']; ?></td>
        		</tr>
        		<tr>
        			<td width="25%"><label for="search_filter"><?php echo $DGTEXT['SEARCHFILTER']; ?>:</label></td>
        			<td>
        		        <?php
        		        if ($data->settings['search_filter'] == 'Y') {
        		            $checked = 'checked="checked"';
        		        } else {
        		            $checked = '';
        		        }
        		        ?>
        		        <input type="checkbox" value="Y" name="search_filter" id="search_filter" <?php echo $checked; ?> />
        		    </td>
        		</tr>
        		<tr>
        			<td width="25%"><label for="file_size_round"><?php echo $DGTEXT['FILE_ROUNDUP']; ?>:</label></td>
        			<td>
        		        <?php
        		        if ($data->settings['file_size_roundup'] == '1') {
        		            $checked = 'checked="checked"';
        		        } else {
        		            $checked = '';
        		        }
        		        ?>
        		        <input type="checkbox" value="1" name="file_size_round" id="file_size_round" <?php echo $checked; ?> />
        		    </td>
        		</tr>
                <tr>
        			<td width="25%"><label for="file_size_decimals"><?php echo $DGTEXT['FILE_DECIMALS']; ?>:</label></td>
        			<td>
        				<?php $decicount = stripslashes($data->settings['file_size_decimals']); ?>
        				<?php if ($decicount == "") { $decicount = 0; } ?>
        				<select name="file_size_decimals" id="file_size_decimals">
        					<option value ="0" <?php if ($decicount == 0) { echo "selected='selected'"; } ?> >0</option>
        					<option value ="1" <?php if ($decicount == 1) { echo "selected='selected'"; } ?> >1</option>
        					<option value ="2" <?php if ($decicount == 2) { echo "selected='selected'"; } ?> >2</option>
        					<option value ="3" <?php if ($decicount == 3) { echo "selected='selected'"; } ?> >3</option>
        					<option value ="4" <?php if ($decicount == 4) { echo "selected='selected'"; } ?> >4</option>
        				</select>
        		    </td>
        		</tr>
        		<tr>
        			<td width="25%"><?php echo $DGTEXT['FILE_TYPE_EXT']; ?>:<br />
                        <span class="smaller"><?php echo $DGTEXT['FILE_TYPE_EXT_INFO'] ?></span></td>
        			<td>
        				<table width="98%">
        				<?php foreach($data->fileext as $ext): ?>
        					<tr>
        						<td width="20" style="padding-left: 5px;">
        							<a href="<?php echo $data->self_link ?>/modify_extensions.php?page_id=<?php echo $page_id; ?>&amp;section_id=<?php echo $section_id; ?>&amp;fileext_id=<?php echo $ext['fileext_id']; ?>" title="<?php echo $TEXT['MODIFY']; ?>">
        								<img src="<?php echo THEME_URL; ?>/images/modify_16.png" border="0" alt="Modify - " />
        							</a>
        						</td>
        						<td><?php echo $DGTEXT['FILE_TYPE'].": ".$ext['file_type']; ?></td>
        						<td><?php
        							$temp = (strlen($ext['extensions']) > 55) ? "..." : "";
        							echo substr($ext['extensions'], 0, 55) . $temp;?>
        						</td>
        					</tr>
        				<?php endforeach; ?>
        				</table>
        			</td>
        		</tr>
                <tr>
                    <td><label for="template_dir"><?php echo $DGTEXT['TPLDIR'] ?>:</label></td>
                    <td>
                        <select id="template_dir" name="template_dir">
                        <?php foreach($data->tpldirs as $dir): ?>
                            <option value="<?php echo $dir ?>"<?php if($data->settings['tpldir'] == $dir): echo ' selected="selected"'; endif;?>><?php echo $dir ?></option>
                        <?php endforeach; ?>
                        </select>&nbsp;&nbsp;
                        <input type="checkbox" name="use_default_css" id="use_default_css"<?php if($data->settings['tplcss'] == 'Y'): echo ' checked="checked"'; endif;?> />
                        <label for="use_default_css"> <?php echo $DGTEXT['TPLCSS'] ?></label>
                    </td>
                </tr>
        		<tr>
        			<td width="25%"><?php echo $DGTEXT['ORDERING']; ?>:</td>
        			<td>
        				<label for="ordering_1"><input type="radio" name="ordering" id="ordering_1" value="1"<?php if($data->settings['ordering']==1): ?> checked="checked"<?php endif; ?> /> <?php echo $DGTEXT['MANUAL'] ?></label><br />
                        <label for="ordering_2"><input type="radio" name="ordering" id="ordering_2" value="2"<?php if($data->settings['ordering']==2): ?> checked="checked"<?php endif; ?> /> <?php echo $DGTEXT['TITLE'], ", ", $DGTEXT['ASCENDING'] ?></label><br />
                        <label for="ordering_3"><input type="radio" name="ordering" id="ordering_3" value="3"<?php if($data->settings['ordering']==3): ?> checked="checked"<?php endif; ?> /> <?php echo $DGTEXT['TITLE'], ", ", $DGTEXT['DESCENDING'] ?></label><br />
        			</td>
        		</tr>
        		<tr class="gradient2">
        			<td>
        				<input name="save" type="submit" value="<?php echo $TEXT['SAVE']; ?>" class="gradient1" />
        			</td>
        			<td style="text-align:right">
        				<input type="button" value="<?php echo $TEXT['CANCEL']; ?>" class="gradient1" onclick="javascript:window.location='<?php echo ADMIN_URL; ?>/pages/modify.php?page_id=<?php echo $page_id; ?>';" />
        			</td>
        		</tr>
            </tbody>
    	</table>
    </form>
</div>
